version: '3.8'
services:
  cyber-api:
    container_name: 'cyber_api'
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - TZ=Asia/Bangkok
    ports:
      - '3002:8080'
    volumes:
      - '/home/istad_lms/images:/home/cyber/media'
