version: '3.8'
services:
  api:
    container_name: 'cyber_api'
    volumes:
      - ./clone_repos:/app/clone_repos
      - ./filestorage/images/:/app/filestorag/images
      - /var/run/docker.sock:/var/run/docker.sock
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - TZ=Asia/Bangkok
    privileged: true  # Grant additional privileges for Docker-in-Docker
    ports:
      - "4011:8080"
    networks:
      - cyber_network
    # Define environment variables or additional settings here if needed

networks:
  cyber_network:
    driver: bridge
