version: '3.8'
services:
  cyber-api:
    container_name: 'cyber_api'
    volumes:
      - /clone_repos:/app/clone_repos
      - /var/run/docker.sock:/var/run/docker.sock
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - TZ=Asia/Bangkok
    ports:
      - '3003:8080'
