server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://136.228.158.126:4015/api
    username: postgres
    password: lyhou123
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 5MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect


  # mail client configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: "lyhou282@gmail.com"
    password: "nizm fijt ltqk mtfi"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


springdoc:
  swagger-ui:
    path: '/'

sonar:
  token: squ_4712e2e165541f9603115c49ff9bea9db801e451 #squ_1e3de797cb64c4ab682051d94c3ee7b3fc40ea33
  url: http://136.228.158.126:4014


my-app:
  state: prod

git:
  clone_directory: /clone_repos/

file_storage:
  image_location: "filestorage/images/"
  client_path: "/images/**"


# This is for the access token
ACCESS_TOKEN_PRIVATE_KEY_PATH: access-refresh-token-keys/access-token-private.key
ACCESS_TOKEN_PUBLIC_KEY_PATH: access-refresh-token-keys/access-token-public.key
# This is for the refresh token
REFRESH_TOKEN_PRIVATE_KEY_PATH: access-refresh-token-keys/refresh-token-private.key
REFRESH_TOKEN_PUBLIC_KEY_PATH: access-refresh-token-keys/refresh-token-public.key
